gitlab:
  image: gitlab/gitlab-ce
  container_name: gitlab
  hostname: gitlab.example.com
  ports:
    - "8443:443"
    - "8080:80"
    - "8022:22"
  volumes_from:
    - gitlab_data

gitlab_data:
  image: alpine
  command: /bin/true
  container_name: gitlab-data
  volumes:
    - /etc/gitlab
    - /var/log/gitlab
    - /var/opt/gitlab

gitlab_runner:
  build: .
  command: "/bin/sh"
  container_name: gitlab-runner
  environment:
    CI_SERVER_URL: http://gitlab.example.com:80/ci
    DOCKER_IMAGE: alpine
    REGISTRATION_TOKEN: XXXXXXXXXXXXXX
    RUNNER_EXECUTOR: docker
  links:
    - gitlab:gitlab.example.com
